# ===============================
# MySQL
# ===============================

spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# ===============================
# JWT
# ===============================

jwt.secret.key=${JWT_SECRET}
jwt.exp.time=3600000

# ===============================
# Logging
# ===============================

logging.level.root=INFO
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

# ===============================
# Error Handling
# ===============================
#
#server.error.include-message=never
#server.error.include-stacktrace=never
#server.error.include-binding-errors=never